### ISSUE TITLE
<C-h> shadowing my YCM mapping

### ISSUE THREAD

**Issue by perrin4869** [Raimondi/delimitMate#204]
It is probably a problem with the order in which plugins are loaded but delimitMate keeps shadowing the mapping I configured for YCM and I can't manage to unmap it. The result of running `:verbose imap <C-h>` is:

```
i  <C-H>        @<Plug>delimitMateBS
        Last set from ~/dotfiles/vim/bundle/delimitMate/plugin/delimitMate.vim
i  <C-H>       * <C-X><C-O><C-P>
        Last set from ~/dotfiles/vim/bundle/YouCompleteMe/autoload/youcompleteme.vim
```

The other weird thing I found looking at delimitMate.vim was the following:

```
    if maparg('<BS>'. 'i') == ''
      silent! imap <unique> <buffer> <BS> <Plug>delimitMateBS
    endif
    if maparg('<C-h>'. 'i') == ''
      silent! imap <unique> <buffer> <C-h> <Plug>delimitMateBS
    endif
```
For some reason maparg isn't using commas to separate its arguments but dots. Changing them to commas didn't fix the issue though.
Thanks!

**Comment by qstrahl** [comment]
Those aren't separate arguments; that dot is the string concatenation
operator.

**Comment by perrin4869** [comment]
The thing is, wasn't the intended purpose to check if <C-h> is already mapped in insert mode? That is not accomplished if you concatenate strings...

**Comment by RGBD** [comment]
Hi there. it seems to be a hidden bug, however, **does not** change the behavior of the plugin itself. See [my pull request](https://github.com/Raimondi/delimitMate/issues/215) for more. I'm not sure, if it will fix the issue, since i could not reproduce it myself.

**Comment by Raimondi** [comment]
That is a typo, I have already merged RGBD's PR and I can't reproduce the issue.

**Comment by perrin4869** [comment]
I noticed that on some files (for example, java files) the issue still persists... Javascript files for example seem to work fine. I don't know why some files work and others don't. Maybe it's the order in which the plugins are loaded. I don't know how to reproduce this either... but I think it might be a good idea to rework how delimitMate handles mapping by making it configurable with global and local variables, as in ycm or ultisnips or easymotion, since that works like charm and does not depend on the order that the scripts are loaded and it's more... elegant: 

```
let g:ycm_key_invoke_completion = '<C-h>'
```

or ultisnips:

```
 let g:UltiSnipsExpandTrigger="<c-e>"¬
```

I think I could put together a pull request for this
